version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: pySQL
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .  # This line specifies the build context directly, without a separate 'context' field.
    depends_on:
      - mysql

volumes:
  mysql_data:
